#!/usr/bin/env python3
"""
Seed script for GuelmaGuide — populates the database with real data about Guelma, Algeria.
Idempotent: can run multiple times safely.
Source: Wikipedia EN/FR (https://en.wikipedia.org/wiki/Guelma)
"""
import sys
import os
import json

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from sqlalchemy import create_engine
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.place import Place, PlaceCategory

engine = create_engine(settings.DATABASE_URL)

SEED_PLACES = [
    # ─── Roman & Ancient Sites ────────────────────────────────────────
    {
        "name": "Roman Theatre of Guelma",
        "name_ar": "مسرح قالمة الروماني",
        "name_en": "Roman Theatre of Guelma",
        "description": "1st-century Roman theatre built by Annia Aelia Restituta. 28 rows, 4,500 seats. Reconstructed 1902-1918. Hosts the Roman Museum.",
        "description_ar": "مسرح روماني من القرن الأول بناه الكاهنة أنيا أليا ريستيتوتا. أُعيد بناؤه 1902-1918. يتسع لـ 4500 متفرج ويضم المتحف الروماني.",
        "description_en": "1st-century Roman theatre built by Annia Aelia Restituta. 28 rows, 4,500 seats. Reconstructed 1902-1918. Hosts the Roman Museum.",
        "latitude": 36.467207,
        "longitude": 7.43007,
        "category": "culture",
        "theme": "roman heritage",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/5/55/Th%C3%A9%C3%A2tre_romain_de_Guelma_8.JPG", "https://upload.wikimedia.org/wikipedia/commons/4/41/Th%C3%A9%C3%A2tre_romain_de_Guelma_27.JPG", "https://upload.wikimedia.org/wikipedia/commons/6/67/Th%C3%A9%C3%A2tre_romain_de_Guelma_2.JPG", "https://upload.wikimedia.org/wikipedia/commons/e/ed/The_Roman_theatre_of_Guelma_02.jpg"],
        "featured": True,
        "rating_avg": 4.6,
        "rating_count": 0,
    },
    {
        "name": "Héliopolis Roman Pool",
        "name_ar": "مسبح هليوبوليس الروماني",
        "name_en": "Héliopolis Roman Pool",
        "description": "Famous circular Roman pool. Origin of the name Heliopolis — City of the Sun. Used for 2,000 years.",
        "description_ar": "مسبح روماني دائري يعكس أشعة الشمس، أصل اسم هليوبوليس (مدينة الشمس). مجمع حراري قديم يُستخدم منذ 2000 سنة.",
        "description_en": "Famous circular Roman pool. Origin of the name Heliopolis - City of the Sun. Used for 2,000 years.",
        "latitude": 36.502778,
        "longitude": 7.444722,
        "category": "culture",
        "theme": "roman heritage thermal",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/d/d0/Guelma._bain.jpg"],
        "featured": True,
        "rating_avg": 4.3,
        "rating_count": 0,
    },
    {
        "name": "Hammam Bradaa Roman Bath",
        "name_ar": "حمام برادع الروماني",
        "name_en": "Hammam Bradaa Roman Bath",
        "description": "Ancient Roman thermal bath complex in the Guelma region. One of the Aquae Thiblitanae sites where Romans installed facilities still present today.",
        "description_ar": "مجمع حمامات رومانية حرارية قديمة. أحد مواقع أكوي ث Blebitanae حيث لا تزال المرافق الرومانية موجودة.",
        "description_en": "Ancient Roman thermal bath. Part of Aquae Thiblitanae. Roman facilities still present.",
        "latitude": 36.4650,
        "longitude": 7.4250,
        "category": "thermal_baths",
        "theme": "roman thermal heritage",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/9/9f/Hammam_Meskhoutine.jpg"],
        "featured": False,
        "rating_avg": 4.0,
        "rating_count": 0,
    },
    {
        "name": "Roknia Dolmens Necropolis",
        "name_ar": "مدفن روكنيا الدولمنز",
        "name_en": "Roknia Dolmens Necropolis",
        "description": "Paleolithic archaeological site with over 3,000 dolmens spread across the landscape. Human occupation since the Paleolithic era. A 4,000+ year window into prehistoric North Africa.",
        "description_ar": "موقع أثري من العصر الحجري القديم يضم أكثر من 3000 دولمن. وجود بشري منذ العصر الحجري. نافذة على شمال أفريقيا القديمة.",
        "description_en": "Paleolithic site with 3,000+ dolmens. Human occupation since Paleolithic. 4,000-year window into prehistoric North Africa.",
        "latitude": 36.55,
        "longitude": 7.23333,
        "category": "culture",
        "theme": "prehistory archaeology",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/2/23/GM_Guelma_Roknia01.jpg"],
        "featured": True,
        "rating_avg": 4.2,
        "rating_count": 0,
    },
    {
        "name": "Byzantine City Walls",
        "name_ar": "أسوار المدينة البيزنطية",
        "name_en": "Byzantine City Walls",
        "description": "Walls built by Byzantine rulers to protect ancient Calama from invasions. Constructed on Roman foundations, visible in several parts of the old town.",
        "description_ar": "أسوار بناها الحكام البيزنطيون لحماية كالاما القديمة. مبنية على أساسات رومانية مرئية في عدة أجزاء من المدينة القديمة.",
        "description_en": "Byzantine walls built on Roman foundations to protect ancient Calama from invasions.",
        "latitude": 36.4630,
        "longitude": 7.4310,
        "category": "culture",
        "theme": "byzantine heritage",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/f/fd/Guelma_seen_from_Ben_Djerrah.jpeg", "https://upload.wikimedia.org/wikipedia/commons/3/34/Guelma_rue.JPG"],
        "featured": False,
        "rating_avg": 3.8,
        "rating_count": 0,
    },

    # ─── Thermal Baths ────────────────────────────────────────────────
    {
        "name": "Hammam Maskhoutine",
        "name_ar": "حمام المسخوطين",
        "name_en": "Hammam Maskhoutine (Bath of the Damned)",
        "description": "Group of 10 thermal springs. Temperature 98\u00b0C, flow 1,650 L/s. Multicolored travertine walls. Legend: wedding party turned to stone by divine curse. Therapeutic for rheumatism and arthritis.",
        "description_ar": "مجموعة من 10 ينابيع حرارية. حرارة 98 درجة، تدفق 1650 لتر/ثانية. جدران متعددة الألوان. أسطورة: حفل زفاف تحجر بلعنة إلهية.",
        "description_en": "10 thermal springs, 98\u00b0C, 1,650 L/s. Multicolored travertine. Therapeutic for rheumatism. Legend of wedding party turned to stone.",
        "latitude": 36.4613,
        "longitude": 7.2637,
        "category": "thermal_baths",
        "theme": "thermal wellness heritage",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/9/9f/Hammam_Meskhoutine.jpg", "https://upload.wikimedia.org/wikipedia/commons/1/17/Des_touriste_locale_du_Hammam_Meskhoutine.JPG", "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hammam_Meskhoutine_vu_d%27en_bas_4.JPG", "https://upload.wikimedia.org/wikipedia/commons/3/3e/Hammam_Meskhoutine_vue_g%C3%A9n%C3%A9rale_1.JPG", "https://upload.wikimedia.org/wikipedia/commons/0/07/Hammam_Meskhoutine_vu_d%27en_bas.JPG"],
        "featured": True,
        "rating_avg": 4.7,
        "rating_count": 0,
    },
    {
        "name": "Hammam Chellala Complex",
        "name_ar": "مجمع حمام الشلالة",
        "name_en": "Hammam Chellala Complex",
        "description": "Modern thermal complex built at the legendary thermal site. Hot waterfall cascade. Mineral-rich waters with iron and calcium carbonate.",
        "description_ar": "مجمع حراري حديث مبني في الموقع الأسطوري. شلال حراري. مياه غنية بالحديد وكربونات الكالسيوم.",
        "description_en": "Modern thermal complex at legendary site. Hot waterfall. Mineral-rich water with iron and calcium carbonate.",
        "latitude": 36.4615,
        "longitude": 7.2640,
        "category": "thermal_baths",
        "theme": "thermal wellness",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/3/3e/Hammam_Meskhoutine_vue_g%C3%A9n%C3%A9rale_1.JPG", "https://upload.wikimedia.org/wikipedia/commons/b/b1/Hammam_Meskhoutine_vu_d%27en_bas_4.JPG", "https://upload.wikimedia.org/wikipedia/commons/5/50/Hammam_Meskhoutine_vu_d%27en_bas_2.JPG"],
        "featured": False,
        "rating_avg": 4.5,
        "rating_count": 0,
    },
    {
        "name": "Hammam N'Bail",
        "name_ar": "حمام النعالة",
        "name_en": "Hammam N'Bail",
        "description": "Mountain thermal resort in eastern Guelma province. Healing waters for rheumatism and skin conditions. Near Guelta Zarga (Blue Lake).",
        "description_ar": "منتجع حراري جبلي. مياه علاجية للروماتيزم وأمراض الجلد. بالقرب من قلتة الزرقاء (الواحة الزرقاء).",
        "description_en": "Mountain thermal resort. Healing waters for rheumatism and skin conditions. Near Guelta Zarga (Blue Lake).",
        "latitude": 36.5200,
        "longitude": 7.6500,
        "category": "thermal_baths",
        "theme": "thermal wellness mountain",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/8/86/Hammam_N%27bails%2C_24220.jpg", "https://upload.wikimedia.org/wikipedia/commons/5/53/Hammam_N%27bails%2C_Alg%C3%A9rie_%28vue_no_5%29.jpg"],
        "featured": False,
        "rating_avg": 4.4,
        "rating_count": 0,
    },
    {
        "name": "A\u00efn Abid Thermal Springs",
        "name_ar": "ينابيع عين عبيد الحرارية",
        "name_en": "A\u00efn Abid Thermal Springs",
        "description": "Natural springs in the mountain village of A\u00efn Abid, 45km from Guelma city. Cold mineral springs alongside warm sources.",
        "description_ar": "ينابيع طبيعية في قرية عين عبيد الجبلية. ينابيع معدنية باردة ودافئة.",
        "description_en": "Natural springs in mountain village of A\u00efn Abid. Cold and warm mineral springs.",
        "latitude": 36.4200,
        "longitude": 7.1800,
        "category": "thermal_baths",
        "theme": "thermal nature",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/9/9f/Hammam_Meskhoutine.jpg"],
        "featured": False,
        "rating_avg": 4.1,
        "rating_count": 0,
    },

    # ─── Nature & Outdoor ─────────────────────────────────────────────
    {
        "name": "Mont Maouna",
        "name_ar": "جبل ونة",
        "name_en": "Mont Maouna",
        "description": "Highest mountain near Guelma. Hiking destination with panoramic views. Part of the Atlas range. Mediterranean conifer forests at higher altitudes: Atlas cedar, Algerian fir, black pine.",
        "description_ar": "أعلى جبل قرب قالمة. وجهة للمشي وإطلالات بانورامية. جزء من سلسلة الأطلس. غابات صنوبرية: أرز الأطلس، تنوب الجزائري.",
        "description_en": "Highest mountain near Guelma. Panoramic views. Atlas range with Atlas cedar and Algerian fir forests.",
        "latitude": 36.4800,
        "longitude": 7.3800,
        "category": "nature",
        "theme": "hiking mountain adventure",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/0/04/GM_Guelma_Maouna02.jpg", "https://upload.wikimedia.org/wikipedia/commons/f/f5/GM_Guelma_Maouna03.jpg"],
        "featured": True,
        "rating_avg": 4.5,
        "rating_count": 0,
    },
    {
        "name": "Oued Zenati River Valley",
        "name_ar": "وادي نهر زناطي",
        "name_en": "Oued Zenati River Valley",
        "description": "Major river system flowing through Guelma Province. Valley with Numidian-era military outposts. Picnic areas along the banks, especially near Oued Zenati town (55,000 population).",
        "description_ar": "نظام نهري رئيسي يمر بولاية قالمة. وادي به مواقع عسكرية نوميدية. مناطق نزهه على الضفاف.",
        "description_en": "Major river system through Guelma Province. Numidian military outposts. Picnic areas along banks.",
        "latitude": 36.316667,
        "longitude": 7.166667,
        "category": "nature",
        "theme": "river picnic nature photography",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/4/45/PANO_20170308_130322.jpg"],
        "featured": False,
        "rating_avg": 4.2,
        "rating_count": 0,
    },
    {
        "name": "Seybouse Valley Farmlands",
        "name_ar": " valley وادي السبوس الزراعي",
        "name_en": "Seybouse Valley Farmlands",
        "description": "Rich agricultural valley surrounding Guelma city. Irrigated zone producing grains and vegetables. Guelma sits at the heart of a large agricultural region at 290m altitude.",
        "description_ar": "وادي زراعي غني يحيط بمدينة قالمة. منطقة مروية تنتج الحبوب والخضروات.",
        "description_en": "Rich agricultural valley. Irrigated zone for grains and vegetables. Guelma at 290m altitude.",
        "latitude": 36.4500,
        "longitude": 7.4200,
        "category": "nature",
        "theme": "agriculture countryside photography",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/1/1d/Route_Annaba_Guelma.jpg", "https://upload.wikimedia.org/wikipedia/commons/b/b5/Champ_de_bl%C3%A9_Guelma_1.jpg"],
        "featured": False,
        "rating_avg": 3.9,
        "rating_count": 0,
    },
    {
        "name": "Barrage Guelma (Dam)",
        "name_ar": "سد قالمة",
        "name_en": "Guelma Dam",
        "description": "Reservoir providing irrigation for the large agricultural perimeter. Birdwatching hotspot. Morning fog over the water creates atmospheric photography conditions.",
        "description_ar": "خزان يوفر الري للمحيط الزراعي. نقطة ممتازة لمراقبة الطيور. ضباب الصباح على الماء يخلق ظروفاً تصويرية.",
        "description_en": "Reservoir for agricultural irrigation. Birdwatching hotspot. Atmospheric morning fog photography.",
        "latitude": 36.4400,
        "longitude": 7.4000,
        "category": "nature",
        "theme": "water birds photography peaceful",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/b/b0/%D8%A8%D9%8E%D8%AD%D9%90%D9%8A%D8%B1%D9%8E%D8%A9_%D8%A8%D9%8F%D9%88%D8%AD%D9%8E%D9%85%D8%AF%D8%A7%D9%86.jpg"],
        "featured": False,
        "rating_avg": 4.0,
        "rating_count": 0,
    },
    {
        "name": "Roum Echallaha Forest",
        "name_ar": "غابة الروحابة",
        "name_en": "Roum Echallaha Forest",
        "description": "One of the major forests in eastern Algeria. 31% of Guelma Province is forested. Nature walks, wildlife observation, seasonal mushroom foraging.",
        "description_ar": "واحدة من الغابات الرئيسية في شرق الجزائر. 31% من ولاية قالمة غابات. مشي في الطبيعة، مراقبة الحياة البرية.",
        "description_en": "Major forest in eastern Algeria. 31% of province forested. Nature walks and wildlife observation.",
        "latitude": 36.4000,
        "longitude": 7.4800,
        "category": "forest",
        "theme": "forest nature hike wildlife",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/2/25/GM_Guelma_Road01.jpg"],
        "featured": False,
        "rating_avg": 4.1,
        "rating_count": 0,
    },
    {
        "name": "D\u00e9fil\u00e9 d\u2019A\u00efn T\u00e9mouchent",
        "name_ar": "مضيق عين تموشنت",
        "name_en": "D\u00e9fil\u00e9 d\u2019A\u00efn T\u00e9mouchent",
        "description": "Scenic gorge/canyon near A\u00efn T\u00e9mouchent area. Hiking and geological formations. Part of the Tell Atlas chain.",
        "description_ar": "مضيق/وادٍ ضيق جميل بالقرب من منطقة عين تموشنت. مشي وتشكيلات جيولوجية. جزء من سلسلة الأطلس التلي.",
        "description_en": "Scenic gorge near A\u00efn T\u00e9mouchent. Hiking and geological formations. Tell Atlas.",
        "latitude": 36.3700,
        "longitude": 7.2800,
        "category": "nature",
        "theme": "hike geology adventure",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/0/04/GM_Guelma_Maouna02.jpg"],
        "featured": False,
        "rating_avg": 4.3,
        "rating_count": 0,
    },
    {
        "name": "Tamlouka",
        "name_ar": "تملكة",
        "name_en": "Tamlouka",
        "description": "Village known for natural parks and springs at altitude of 847m. Off the beaten path. Cool climate in summer compared to lowland Guelma.",
        "description_ar": "قرية تشتهر بحدائق طبيعية وينابيع على ارتفاع 847م. من المسارات غير التقليدية.",
        "description_en": "Village with natural parks at 847m altitude. Off the beaten path. Cool summer climate.",
        "latitude": 36.1500,
        "longitude": 7.13333,
        "category": "nature",
        "theme": "village nature cool climate",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/f/f5/GM_Guelma_Maouna03.jpg"],
        "featured": False,
        "rating_avg": 3.7,
        "rating_count": 0,
    },

    # ─── Sports ───────────────────────────────────────────────────────
    {
        "name": "Stade Guelma",
        "name_ar": "ملعب قالمة",
        "name_en": "Stade Guelma",
        "description": "Community football stadium. Local matches on weekends. Social gathering point for families and youth.",
        "description_ar": "ملعب كرة قدم مجتمعي. مباريات محلية في عطلة نهاية الأسبوع. نقطة تجمع للعائلات والشباب.",
        "description_en": "Community football stadium. Weekend matches. Social gathering point.",
        "latitude": 36.4520,
        "longitude": 7.4350,
        "category": "sports",
        "theme": "football sports community",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/d/d3/Stade_Souidani_Boujemaa_%28Guelma%2C_Algeria%29.jpg"],
        "featured": False,
        "rating_avg": 3.9,
        "rating_count": 0,
    },
    {
        "name": "University Sports Complex",
        "name_ar": "المجمع الرياضي الجامعي",
        "name_en": "University Sports Complex",
        "description": "Sports facilities at University 8 Mai 1945 Guelma (17,530 students). Athletics, indoor courts, swimming pool access for students and local community.",
        "description_ar": "مرافق رياضية في جامعة 8 ماي 1945 قالمة. ألعاب قوى، ملاعب داخلية، مسبح.",
        "description_en": "University sports facilities for students and community. Athletics, indoor courts, pool.",
        "latitude": 36.4580,
        "longitude": 7.4280,
        "category": "sports",
        "theme": "university sports swim gym",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/b/b5/Champ_de_bl%C3%A9_Guelma_1.jpg"],
        "featured": False,
        "rating_avg": 3.8,
        "rating_count": 0,
    },

    # ─── Culture & Heritage ───────────────────────────────────────────
    {
        "name": "Guelma Central Market",
        "name_ar": "السوق المركزي بقالمة",
        "name_en": "Guelma Central Market",
        "description": "Traditional Algerian market known for local produce: grains, olive oil, spices. Handmade crafts. Traditional Guelma pastries: tchenika, msemen, baklava. Best visited in the morning.",
        "description_ar": "سوق تقليدي للمنتجات المحلية: حبوب، زيت زيتون، توابل. حرف يدوية. حلويات قالمية: تشنيكة، مسمن، بقلاوة. أفضل زيارة صباحاً.",
        "description_en": "Traditional market: grains, olive oil, spices, crafts. Guelma pastries: tchenika, msemen. Visit in morning.",
        "latitude": 36.4500,
        "longitude": 7.4300,
        "category": "culture",
        "theme": "market food crafts shopping social",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/f/f8/GM_Guelma_Center01.jpg", "https://upload.wikimedia.org/wikipedia/commons/4/48/General_view_of_Guelma.jpg"],
        "featured": False,
        "rating_avg": 4.0,
        "rating_count": 0,
    },
    {
        "name": "Mus\u00e9e Romain de Guelma",
        "name_ar": "المتحف الروماني بقالمة",
        "name_en": "Guelma Roman Museum",
        "description": "Housed within the restored Roman Theatre. Exhibits ancient Calama artifacts, mosaics, inscriptions from the Numidian and Roman periods.",
        "description_ar": "داخل المسرح الروماني المُرمم. يعرض آثار كالاما الأثرية، فسيفساء، نقوش نوميدية ورومانية.",
        "description_en": "Roman museum inside the theater. Ancient Calama artifacts, mosaics, inscriptions.",
        "latitude": 36.4675,
        "longitude": 7.4295,
        "category": "culture",
        "theme": "museum history education",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/4/41/Th%C3%A9%C3%A2tre_romain_de_Guelma_27.JPG", "https://upload.wikimedia.org/wikipedia/commons/2/27/The_museum_of_the_Roman_theatre_02.jpg", "https://upload.wikimedia.org/wikipedia/commons/9/93/The_museum_of_the_Roman_theatre_03.jpg", "https://upload.wikimedia.org/wikipedia/commons/0/05/The_museum_of_the_Roman_theatre_04.jpg", "https://upload.wikimedia.org/wikipedia/commons/d/d9/The_museum_of_the_Roman_theatre_05.jpg", "https://upload.wikimedia.org/wikipedia/commons/5/57/The_museum_of_the_Roman_theatre_06.jpg"],
        "featured": True,
        "rating_avg": 4.4,
        "rating_count": 0,
    },
    {
        "name": "Notre-Dame de Guelma Church",
        "name_ar": "كنيسة سيدة قالمة",
        "name_en": "Notre-Dame de Guelma Church",
        "description": "Historic church from the French colonial period. Part of Guelma\u2019s cultural heritage landscape. Regular services, also open to visitors.",
        "description_ar": "كنيسة تاريخية من الفترة الاستعمارية الفرنسية. جزء من التراث الثقافي لقالمة. regular open to visitors.",
        "description_en": "Historic colonial-era church. Part of Guelma cultural heritage. Open to visitors.",
        "latitude": 36.4540,
        "longitude": 7.4320,
        "category": "culture",
        "theme": "architecture religion heritage",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/6/6c/Th%C3%A9%C3%A2tre_Municipal_de_Guelma.jpg"],
        "featured": False,
        "rating_avg": 3.7,
        "rating_count": 0,
    },
    {
        "name": "University 8 Mai 1945",
        "name_ar": "جامعة 8 ماي 1945",
        "name_en": "University 8 Mai 1945 Guelma",
        "description": "Major university with 17,530 students, 7 faculties, 23 research labs. Cultural events, open lectures, student activities. Hub of youth life in the city.",
        "description_ar": "جامعة كبرى بـ 17,530 طالب، 7 كليات، 23 مختبر بحثي. فعاليات ثقافية، محاضرات مفتوحة.",
        "description_en": "17,530 students, 7 faculties, 23 research labs. Cultural events and youth hub.",
        "latitude": 36.4580,
        "longitude": 7.4260,
        "category": "culture",
        "theme": "education youth culture events",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/7/73/8_Mai_1945_Memorial_Statue.jpg"],
        "featured": False,
        "rating_avg": 3.6,
        "rating_count": 0,
    },

    # ─── Relaxation & Wellness ────────────────────────────────────────
    {
        "name": "Hammam Debagh Spa Resort",
        "name_ar": "منتجع حمام دباغ الصحي",
        "name_en": "Hammam Debagh Spa Resort",
        "description": "Full thermal spa experience at the famous Hammam Maskhoutine valley. Professional wellness center. Mineral water therapy, mud treatments, relaxation pools.",
        "description_ar": "تجربة سبا حراري كامل في وادي حمام المسخوطين. مركز صحي احترافي. علاج بالمياه المعدنية، علاج بالطين.",
        "description_en": "Full thermal spa. Professional wellness center. Mineral water therapy, mud treatments.",
        "latitude": 36.4610,
        "longitude": 7.2635,
        "category": "relaxation",
        "theme": "spa wellness thermal retreat",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/1/17/Des_touriste_locale_du_Hammam_Meskhoutine.JPG", "https://upload.wikimedia.org/wikipedia/commons/2/24/Hammam_Debagh_%D8%AD%D9%85%D8%A7%D9%85_%D8%AF%D8%A8%D8%A7%D8%BA_02.jpg", "https://upload.wikimedia.org/wikipedia/commons/b/bd/Hammam_Debagh_%D8%AD%D9%85%D8%A7%D9%85_%D8%AF%D8%A8%D8%A7%D8%BA_03.jpg", "https://upload.wikimedia.org/wikipedia/commons/5/5b/Hammam_Debagh_%D8%AD%D9%85%D8%A7%D9%85_%D8%AF%D8%A8%D8%A7%D8%BA_04.jpg"],
        "featured": True,
        "rating_avg": 4.6,
        "rating_count": 0,
    },
    {
        "name": "Maouna Summit Viewpoint",
        "name_ar": "إطلالة قمة جبل ونة",
        "name_en": "Maouna Summit Viewpoint",
        "description": "360-degree panoramic view from the highest point of Mont Maouna. See all of Guelma Province on a clear day. Rewarding destination for the hike. Perfect for meditation, photography best at dawn.",
        "description_ar": "إطلالة 360 درجة من أعلى نقطة في جبل ونة. ترى كل ولاية قالمة في يوم صافٍ. وجهة للمشي والتأمل.",
        "description_en": "360\u00b0 panoramic view of all Guelma Province. Perfect for meditation and photography at dawn.",
        "latitude": 36.4890,
        "longitude": 7.3820,
        "category": "relaxation",
        "theme": "yoga meditation nature views",
        "images": ["https://upload.wikimedia.org/wikipedia/commons/0/04/GM_Guelma_Maouna02.jpg", "https://upload.wikimedia.org/wikipedia/commons/f/f5/GM_Guelma_Maouna03.jpg"],
        "featured": True,
        "rating_avg": 4.8,
        "rating_count": 0,
    },
]

SEED_BADGES = [
    {
        "name_ar": "الخطوة الأولى",
        "name_fr": "Le Premier Pas",
        "name_en": "First Step",
        "icon": "👣",
        "description_ar": "أضفت أول مكان للدليل!",
        "description_fr": "Tu as ajout\u00e9 ton premier lieu !",
        "description_en": "Added your first place to the guide!",
        "criteria": {"type": "contributions_count", "count": 1},
    },
    {
        "name_ar": "مستكشف روما",
        "name_fr": "Explorateur Romain",
        "name_en": "Roman Explorer",
        "icon": "🏛️",
        "description_ar": "زرت 5 مواقع رومانية",
        "description_fr": "As visit\u00e9 5 sites romains",
        "description_en": "Visited 5 Roman heritage sites",
        "criteria": {"type": "visit_category", "count": 5, "category": "culture"},
    },
    {
        "name_ar": "باحث حراري",
        "name_fr": "Chercheur Thermal",
        "name_en": "Thermal Seeker",
        "icon": "♨️",
        "description_ar": "زرت جميع الحمامات الحرارية",
        "description_fr": "As visit\u00e9 tous les bains thermaux",
        "description_en": "Visited all thermal baths",
        "criteria": {"type": "visit_category", "count": 4, "category": "thermal_baths"},
    },
    {
        "name_ar": "معلم الجبل",
        "name_fr": "Ma\u00eetre de la Montagne",
        "name_en": "Mountain Master",
        "icon": "⛰️",
        "description_ar": "أكملت تسلق جبل ونة",
        "description_fr": "As compl\u00e9t\u00e9 l\u2019ascension du Maouna",
        "description_en": "Completed the Maouna summit hike",
        "criteria": {"type": "complete_experience", "id": 3},
    },
    {
        "name_ar": "مصور المدينة",
        "name_fr": "Photographe de la Ville",
        "name_en": "City Photographer",
        "icon": "📸",
        "description_ar": "شاركت بـ 10 صور في تحديات التصوير",
        "description_fr": "As soumis 10 photos aux d\u00e9fis photo",
        "description_en": "Submitted 10 photos to photo challenges",
        "criteria": {"type": "photo_submissions", "count": 10},
    },
    {
        "name_ar": "المرشد المحلي",
        "name_fr": "Guide Local",
        "name_en": "Local Guide",
        "icon": "🗺️",
        "description_ar": "ساعد 5 سياح باقتراحاتك",
        "description_fr": "As aid\u00e9 5 touristes avec tes conseils",
        "description_en": "Helped 5 tourists with your tips",
        "criteria": {"type": "tourist_answers", "count": 5},
    },
    {
        "name_ar": "روح المجتمع",
        "name_fr": "Esprit Communautaire",
        "name_en": "Community Spirit",
        "icon": "🤝",
        "description_ar": "حضرت 10 فعاليات جماعية",
        "description_fr": "As particip\u00e9 \u00e0 10 \u00e9v\u00e9nements",
        "description_en": "Attended 10 group events",
        "criteria": {"type": "meetups_attended", "count": 10},
    },
]

def seed():
    with Session(engine) as session:
        placed_count = 0
        skipped_count = 0
        for place_data in SEED_PLACES:
            existing = session.query(Place).filter(
                Place.latitude == place_data["latitude"],
                Place.longitude == place_data["longitude"]
            ).first()
            if existing:
                skipped_count += 1
                print(f"  SKIP: {place_data['name']}")
                continue
            place = Place(**place_data)
            session.add(place)
            placed_count += 1
            print(f"  ADD: {place_data['name']} ({place_data['category']})")

        session.commit()
        print(f"\nDone! Placed: {placed_count}, Skipped (existing): {skipped_count}")
        print(f"Total places in DB: {session.query(Place).count()}")


if __name__ == "__main__":
    seed()
